# TCL File Generated by Component Editor 25.3
# Fri Sep 25 17:35:09 MSK 2026
# DO NOT MODIFY


# 
# system_master "system_master" v1.0
#  2026.09.25.17:35:09
# Avalon-MM Master to RISC-V Bridge
# 

# 
# request TCL package from ACDS 25.3
# 
package require -exact qsys 25.3


# 
# module system_master
# 
set_module_property DESCRIPTION "Avalon-MM Master to RISC-V Bridge"
set_module_property NAME system_master
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property BSP_CPU false
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME system_master
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_property LOAD_ELABORATION_LIMIT 0
set_module_property PRE_COMP_MODULE_ENABLED false
set_module_property DISPLAY_ICON ""


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL system_master
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file system_master.v VERILOG PATH system_master.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""
set_interface_property clock_sink IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property clock_sink SV_INTERFACE_TYPE ""
set_interface_property clock_sink SV_INTERFACE_MODPORT_TYPE ""

add_interface_port clock_sink clk clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""
set_interface_property reset_sink IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property reset_sink SV_INTERFACE_TYPE ""
set_interface_property reset_sink SV_INTERFACE_MODPORT_TYPE ""

add_interface_port reset_sink reset reset Input 1


# 
# connection point avalon_master
# 
add_interface avalon_master avalon start
set_interface_property avalon_master addressGroup 0
set_interface_property avalon_master addressUnits SYMBOLS
set_interface_property avalon_master associatedClock clock_sink
set_interface_property avalon_master associatedReset reset_sink
set_interface_property avalon_master bitsPerSymbol 8
set_interface_property avalon_master burstOnBurstBoundariesOnly false
set_interface_property avalon_master burstcountUnits WORDS
set_interface_property avalon_master doStreamReads false
set_interface_property avalon_master doStreamWrites false
set_interface_property avalon_master holdTime 0
set_interface_property avalon_master linewrapBursts false
set_interface_property avalon_master maximumPendingReadTransactions 0
set_interface_property avalon_master maximumPendingWriteTransactions 0
set_interface_property avalon_master minimumResponseLatency 1
set_interface_property avalon_master readLatency 1
set_interface_property avalon_master readWaitTime 0
set_interface_property avalon_master setupTime 0
set_interface_property avalon_master timingUnits Cycles
set_interface_property avalon_master waitrequestAllowance 0
set_interface_property avalon_master waitrequestTimeout 1024
set_interface_property avalon_master writeWaitTime 0
set_interface_property avalon_master enableConcurrentSubordinateAccess 0
set_interface_property avalon_master optimizedReadsWithBE 0
set_interface_property avalon_master ENABLED true
set_interface_property avalon_master EXPORT_OF ""
set_interface_property avalon_master PORT_NAME_MAP ""
set_interface_property avalon_master CMSIS_SVD_VARIABLES ""
set_interface_property avalon_master SVD_ADDRESS_GROUP ""
set_interface_property avalon_master IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property avalon_master SV_INTERFACE_TYPE ""
set_interface_property avalon_master SV_INTERFACE_MODPORT_TYPE ""

add_interface_port avalon_master master_address address Output 32
add_interface_port avalon_master master_readdata readdata Input 32
add_interface_port avalon_master master_read read Output 1
add_interface_port avalon_master master_write write Output 1
add_interface_port avalon_master master_writedata writedata Output 32
add_interface_port avalon_master master_byteenable byteenable Output 4


# 
# connection point conduit_riscv
# 
add_interface conduit_riscv conduit end
set_interface_property conduit_riscv associatedClock ""
set_interface_property conduit_riscv associatedReset ""
set_interface_property conduit_riscv ENABLED true
set_interface_property conduit_riscv EXPORT_OF ""
set_interface_property conduit_riscv PORT_NAME_MAP ""
set_interface_property conduit_riscv CMSIS_SVD_VARIABLES ""
set_interface_property conduit_riscv SVD_ADDRESS_GROUP ""
set_interface_property conduit_riscv IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property conduit_riscv SV_INTERFACE_TYPE ""
set_interface_property conduit_riscv SV_INTERFACE_MODPORT_TYPE ""

add_interface_port conduit_riscv RISCV_rdata rdata Output 32
add_interface_port conduit_riscv RISCV_wrdata wrdata Input 32
add_interface_port conduit_riscv RISCV_byteenable byteenable Input 4
add_interface_port conduit_riscv RISCV_addr addr Input 20
add_interface_port conduit_riscv RISCV_wr wr Input 1
add_interface_port conduit_riscv RISCV_rd rd Input 1

